apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: rpdharanidhar/devops-task03
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://dharani:dharani@mongodb:27017/test



