apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: rpdharanidhar/devops-task03:latest
        ports:
        - containerPort: 80
      restartPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx